version: "3.9"
services:
  docker-saigneur-discovery:
    image: saigneur-discovery
    container_name: msaigneur-discovery
    build:
      dockerfile: Dockerfile
    ports:
      - "9102:9102"
    restart: always
    links:
      - "docker-saigneur-config-server:saigneur-config-server"
#    depends_on:
#      - docker-saigneur-config-server
    networks:
      - saigneur-network

networks:
  saigneur-network:
    external: true
